baseURL = 'https://lothan.github.io/'
languageCode = 'en-us'
title = 'Joe Lothan'
theme = 'hermit'

[author]
	name = "Joe Lothan"

[params]
	[[params.social]]
		name = "github"
		url = "https://github.com/lothan"